# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      # Issues with Vite
      - dependency-name: "eslint"
        versions: ["9"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions: ["8"]
      - dependency-name: "@typescript-eslint/parser"
        versions: ["8"]
      # Monaco editor not support React 19 until 4.7.0
      - dependency-name: "react"
        versions: [">=19.0.0"]
      - dependency-name: "react-dom"
        versions: [">=19.0.0"]
      - dependency-name: "@types/react"
        versions: [">=19.0.0"]
      - dependency-name: "@types/react-dom"
        versions: [">=19.0.0"]
    groups:
      dev-dependencies:
        patterns:
          - "*"
