checkoutLocation: whatsth.is
additionalRepositories:
  - url: https://github.com/soup-bowl/api.whatsth.is
    checkoutLocation: api.whatsth.is

tasks:
  - name: Backend
    before: cd ../api.whatsth.is
    env:
      REDIS_URL: redis://localhost
      DOTNET_ROOT: /home/gitpod/dotnet
    init: |
      printf 'export PATH="%s:$PATH"\n' "/home/gitpod/dotnet" >> $HOME/.bashrc
      docker pull redis/redis-stack:latest
      mkdir -p /home/gitpod/dotnet
      curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 7.0.100 --install-dir /home/gitpod/dotnet
      /home/gitpod/dotnet/dotnet restore
    command: |
      docker run -d -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
      /home/gitpod/dotnet/dotnet run --project Whatsthis.API
  - name: Frontend
    init: |
      nvm install 18
      npm install
    command: |
      echo "PUBLIC_URL=$(gp url 3000)" > .env.development.local
      echo "REACT_APP_API_URL=$(gp url 43594)" >> .env.development.local
      echo "REACT_APP_VERSION=\$npm_package_version" >> .env.development.local
      cp .env.development.local .env.production.local
      nvm use 18
      npm start
    openMode: split-right

workspaceLocation: whatsth.is/.github/gitpod.code-workspace

ports:
  - port: 3000
    name: Frontend
    description: Access the React PWA app.
    visibility: public
    onOpen: open-browser
  - port: 43594
    name: Backend
    description: Backend Python FastAPI.
    visibility: public
  - port: 8001
    name: Redis GUI
    description: RedisInsight client for the backend API.
    visibility: private
