tasks:
  - init: |
      docker-compose pull
      docker-compose build
      npm install
    command: |
      echo "REACT_APP_API_URL=https://43594-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}" >> .env.development
      docker-compose up
