checkoutLocation: whatsth.is
additionalRepositories:
  - url: https://github.com/soup-bowl/api.whatsth.is
    checkoutLocation: api.whatsth.is

tasks:
  - name: Backend
    before: cd ../api.whatsth.is
    init: |
      docker pull redis/redis-stack:latest
      python -m venv env
      source env/bin/activate
      pip install -r requirements.txt
      pip install pytest
    command: |
      export REDIS_URL="redis://localhost"
      docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
      source env/bin/activate
      uvicorn api.main:app --reload --port 43594
  - name: Frontend
    init: |
      npm install
    command: |
      echo "PUBLIC_URL=$(gp url 3000)" > .env.development.local
      echo "REACT_APP_API_URL=$(gp url 43594)" >> .env.development.local
      echo "REACT_APP_VERSION=\$npm_package_version" >> .env.development.local
      cp .env.development.local .env.production.local
      npm start

workspaceLocation: whatsth.is/.github/gitpod.code-workspace

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 43594
    visibility: public