import {
	SiGithub,
	SiWordpress,
	SiDrupal,
	SiJoomla,
	SiPhp,
	SiDiscourse,
	SiShopify,
	SiWikipedia,
	SiSquarespace,
	SiGoogletagmanager,
	SiGoogleanalytics,
	SiReact,
	SiVuedotjs,
	SiBootstrap,
	SiVimeo,
	SiCloudflare,
	SiAmazonwebservices,
	SiUbuntu,
	SiNginx,
	SiGhost,
	SiKentico,
	SiUmbraco,
	SiVbulletin,
	SiWix,
	SiJekyll,
	SiHugo,
	SiAngular,
	SiJquery,
	SiThreedotjs,
	SiLodash,
	SiAxios,
	SiWistia,
	SiDisqus,
	SiYoast,
	SiApache,
} from "@icons-pack/react-simple-icons"

const iconsMap: { [key: string]: React.ComponentType } = {
	angular: SiAngular,
	apache: SiApache,
	awscloudfront: SiAmazonwebservices,
	axios: SiAxios,
	bootstrap: SiBootstrap,
	cloudflare: SiCloudflare,
	discourse: SiDiscourse,
	disqus: SiDisqus,
	drupal: SiDrupal,
	ghost: SiGhost,
	github: SiGithub,
	githubpages: SiGithub,
	googleanalytics: SiGoogleanalytics,
	googletagmanager: SiGoogletagmanager,
	hugo: SiHugo,
	jekyll: SiJekyll,
	joomla: SiJoomla,
	jquery: SiJquery,
	kentico: SiKentico,
	lodash: SiLodash,
	mediawiki: SiWikipedia,
	nginx: SiNginx,
	php: SiPhp,
	phpbb: SiPhp,
	react: SiReact,
	shopify: SiShopify,
	squarespace: SiSquarespace,
	threedjs: SiThreedotjs,
	ubuntu: SiUbuntu,
	umbraco: SiUmbraco,
	vbulletin: SiVbulletin,
	vimeo: SiVimeo,
	vuejs: SiVuedotjs,
	wistia: SiWistia,
	wix: SiWix,
	wordpress: SiWordpress,
	yoast: SiYoast,
}

export const ServiceIcon = ({ name }: { name: string }) => {
	const normalized = name.toLowerCase().replace(/[\s.-]+/g, "")
	const IconComponent = iconsMap[normalized]

	if (IconComponent === undefined) {
		return <></>
	}

	return <IconComponent />
}
