import cronstrue from "cronstrue";

// JSDocs generated by ChatGPT.

/**
 * Calculates a human-readable description of a cron expression string.
 * 
 * @param {string} input - The cron expression string to parse.
 * @returns {string} A human-readable description of the cron expression, or an error message if the string is invalid.
 */
export const calculateCronString = (input: string) => {
	let output: string = '';
	try {
		output = cronstrue.toString(decodeCronCode(input));
	} catch {
		output = 'Unable to calculate - check string is valid';
	}

	return output;
}

/**
 * Checks if a string is a valid cron expression code.
 *
 * @param {string} input - The string to check.
 * @returns {boolean} True if the string is a valid cron expression code, false otherwise.
 */
export const checkForValidCronCode = (input: string) => {
	if (~[5, 6].indexOf(decodeCronCode(input).split(' ').length)) {
		return true;
	}
	return false;
}

/**
 * Encodes a cron expression code string by replacing spaces with underscores.
 * 
 * @param {string} input - The cron expression code string to encode.
 * @returns {string} The encoded cron expression code string.
 */
export const encodeCronCode = (input: string): string => input.split(' ').join('_');

/**
 * Decodes a cron expression code string by replacing underscores with spaces.
 * 
 * @param {string} input - The cron expression code string to decode.
 * @returns {string} The decoded cron expression code string.
 */
export const decodeCronCode = (input: string): string => input.split('_').join(' ');
